{% set version = "0.18.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-sandpaper
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/carpentries/sandpaper/archive/refs/tags/{{ version }}.tar.gz
  sha256: c11cfc4e6d45eaa56f22d93c5ec196d2f54560938cfccdb50c423b36a0d9affc

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-assertthat
    - r-callr
    - r-cffr
    - r-cli >=3.4.0
    - r-commonmark
    - r-desc
    - r-fs >=1.5.0
    - r-gert >=1.0.1
    - r-gh
    - r-glue
    - r-httr
    - r-knitr >=1.33
    - r-markdown
    - r-pegboard >=0.7.0
    - r-pkgdown >=1.6.0
    - r-renv >=0.14.0
    - r-rlang >=0.4.3
    - r-rmarkdown >=2.4
    - r-rprojroot
    - r-rstudioapi
    - r-servr
    - r-stringr
    - r-usethis >=2.0.0
    - r-whisker
    - r-withr
    - r-yaml
    - r-r.utils
    - r-xfun
  run:
    - r-base
    - r-assertthat
    - r-callr
    - r-cffr
    - r-cli >=3.4.0
    - r-commonmark
    - r-desc
    - r-fs >=1.5.0
    - r-gert >=1.0.1
    - r-gh
    - r-glue
    - r-httr
    - r-knitr >=1.33
    - r-markdown
    - r-pegboard >=0.7.0
    - r-pkgdown >=1.6.0
    - r-renv >=0.14.0
    - r-rlang >=0.4.3
    - r-rmarkdown >=2.4
    - r-rprojroot
    - r-rstudioapi
    - r-servr
    - r-stringr
    - r-usethis >=2.0.0
    - r-whisker
    - r-withr
    - r-yaml
    - r-r.utils
    - r-xfun

test:
  requires:
    - git            # [not win]
    - r-testthat     # [not win]
    - r-mockr        # [not win]
    - r-sessioninfo  # [not win]
    - r-varnish      # [not win]
  source_files:
    - tests/
  commands:
    - $R -e "library('sandpaper')"  # [not win]
    - $R -e "testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)"  # [not win]
    - "\"%R%\" -e \"library('sandpaper')\""  # [win]
    #- "\"%R%\" -e \"testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)\""  # [win]

about:
  home: https://carpentries.github.io/sandpaper/
  license: MIT
  summary: Create and Curate Carpentries Lessons
  description: |
    The {sandpaper} package was created by
    [The Carpentries](https://carpentries.org) to re-imagine our method of
    creating lesson websites for our workshops.
    This package will take a series of
    [Markdown](https://www.markdownguide.org/getting-started/) or
    [RMarkdown](https://rmarkdown.rstudio.com/) files and generate a static
    website with the features and styling of The Carpentries lessons
    including customized layouts and callout blocks.
    Much of the functionality in this package is inspired by
    [Jenny Bryan's](https://jennybryan.org/) work with the
    [{usethis}](https://usethis.r-lib.org/) package.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE
  dev_url: https://github.com/carpentries/sandpaper/
  doc_url: https://carpentries.github.io/sandpaper/

extra:
  recipe-maintainers:
    - conda-forge/r
    - matthewfeickert
